plugins {
	id 'java'
	id 'com.palantir.git-version' version '0.13.0'
}

archivesBaseName = 'processor'
version = versionDetails().lastTag

java {
	sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
	withSourcesJar()
	withJavadocJar()
}

javadoc {
	options {
		links 'https://docs.zaaarf.foo/lillero/'
		links 'https://square.github.io/javapoet/javadoc/javapoet/'
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://maven.fantabos.co' }
}

dependencies {
	implementation 'com.squareup:javapoet:1.13.0'
	implementation 'org.ow2.asm:asm-commons:9.7'
	implementation 'ftbsc:lll:0.6.0'
	implementation 'ftbsc.lll:mapper:0.4.1'
}
